services:
  - type: web
    name: seedsync-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    branch: main                    # Or "master" depending on your repo
    envVars:
      - key: CORS_ORIGINS
        value: "*"                  # Replace with frontend URL in prod
    healthCheckPath: / 